### ISSUE TITLE
What is the "meaningful metric Gg" used in computing CMD of two word?

### ISSUE THREAD

**Issue by heslowen** [context-mover/context-mover-distance-and-barycenters#2]
In paper
![image](https://user-images.githubusercontent.com/22348625/65384670-a31d2400-dd57-11e9-8927-398dcddb2b32.png)

**_How to choose_**  ![image](https://user-images.githubusercontent.com/22348625/65384659-8680ec00-dd57-11e9-991c-5f2cc8f173b8.png) ?
**Another way**，when I get two word embeddings(e.g. both 200 dimension vector), how can I get the matrix **M**? 
![image](https://user-images.githubusercontent.com/22348625/65384838-c9dc5a00-dd59-11e9-9665-76ba98df91a7.png)

Thx!!!~~~

**Comment by sidak** [comment]
You can use L2 distance or angular distance or something of your own choice as well. See https://github.com/context-mover/context-mover-distance-and-barycenters/blob/master/wasserstein.py#L402 for the corresponding code.
